# .github/workflows/ci.yml
name: Node CI
on: [push]

env:
  NODE_VERSION: 18

jobs:
  ci:
    name: CI Steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name:  install
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test:ci
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
